// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/28/2025, 10:25:09 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/river/Projects/oc/nclinic.cz/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/river/Projects/oc/nclinic.cz/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/river/Projects/oc/nclinic.cz/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/river/Projects/oc/nclinic.cz/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/river/Projects/oc/nclinic.cz/app/plugins/**/*.{js,ts,mjs}","/home/river/Projects/oc/nclinic.cz/app/composables/**/*.{js,ts,mjs}","/home/river/Projects/oc/nclinic.cz/app/utils/**/*.{js,ts,mjs}","/home/river/Projects/oc/nclinic.cz/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/river/Projects/oc/nclinic.cz/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/river/Projects/oc/nclinic.cz/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/river/Projects/oc/nclinic.cz/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;